### ISSUE TITLE
Начало проекта, реализация простых классов

### ISSUE THREAD

**Issue by Sakuraboii** [Sakuraboii/TechProgram#2]
Реализовать класс фишки (игровой фишки), в классе должны быть реализованы координаты(int x, int y)

**Comment by blessyoutrap** [comment]
НЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕТ

**Comment by Sakuraboii** [comment]
я уже написал это)))

**Comment by blessyoutrap** [comment]
да я еще два месяца назад крч написал и забыл просто выложить(((((((

**Comment by blessyoutrap** [comment]
бляяяя все я упустил свой шщанс стать програмистом(((((((((((((
