### ISSUE TITLE
Первое задание левона и никиты, давайте хоть почитайте что нибудь пидоры

### ISSUE THREAD

**Issue by Sakuraboii** [Sakuraboii/TechProgram#3]
- Открыть метанит 
- Прочитать статьи по программированию
- Начать делать проект

**Comment by blessyoutrap** [comment]
Здравствуйте, можно более конкретно поставить задачу, вы ставите слишком расплывчатые цели для нас с Левоном

**Comment by Sakuraboii** [comment]
Если понимаете что я написал в коде который вы можете просмотреть в этом же репрозиттории, то можете ничего не читать, а если не понимаете то можете начинать читать сначала

**Comment by Sakuraboii** [comment]
Как проходит выполнение вашего задания?
